# Generated by Django 5.0.6 on 2024-07-13 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIYProject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='image',
            field=models.ImageField(upload_to='images/DIYProjects/ProjectCategory'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('process', models.TextField()),
                ('img_1', models.ImageField(upload_to='images/DIYProjects/ProjectImages')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='images/DIYProjects/ProjectImages')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIYProject.projectcategory')),
            ],
        ),
    ]
