# Generated by Django 5.0.6 on 2024-07-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIYProject', '0004_project_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.CharField(max_length=200),
        ),
    ]
