# Generated by Django 5.0.7 on 2024-07-22 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_time_zone'),
        ('marketplace', '0008_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstep1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
