# Generated by Django 5.0.6 on 2024-07-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_answer_answercomment_answervote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
