# Generated by Django 5.0.7 on 2024-07-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_book_messenger', '0004_conversation_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
